require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GoalDataPtsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # GoalDataPt. As you add validations to GoalDataPt, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GoalDataPtsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all goal_data_pts as @goal_data_pts" do
      goal_data_pt = GoalDataPt.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:goal_data_pts)).to eq([goal_data_pt])
    end
  end

  describe "GET #show" do
    it "assigns the requested goal_data_pt as @goal_data_pt" do
      goal_data_pt = GoalDataPt.create! valid_attributes
      get :show, {:id => goal_data_pt.to_param}, valid_session
      expect(assigns(:goal_data_pt)).to eq(goal_data_pt)
    end
  end

  describe "GET #new" do
    it "assigns a new goal_data_pt as @goal_data_pt" do
      get :new, {}, valid_session
      expect(assigns(:goal_data_pt)).to be_a_new(GoalDataPt)
    end
  end

  describe "GET #edit" do
    it "assigns the requested goal_data_pt as @goal_data_pt" do
      goal_data_pt = GoalDataPt.create! valid_attributes
      get :edit, {:id => goal_data_pt.to_param}, valid_session
      expect(assigns(:goal_data_pt)).to eq(goal_data_pt)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new GoalDataPt" do
        expect {
          post :create, {:goal_data_pt => valid_attributes}, valid_session
        }.to change(GoalDataPt, :count).by(1)
      end

      it "assigns a newly created goal_data_pt as @goal_data_pt" do
        post :create, {:goal_data_pt => valid_attributes}, valid_session
        expect(assigns(:goal_data_pt)).to be_a(GoalDataPt)
        expect(assigns(:goal_data_pt)).to be_persisted
      end

      it "redirects to the created goal_data_pt" do
        post :create, {:goal_data_pt => valid_attributes}, valid_session
        expect(response).to redirect_to(GoalDataPt.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved goal_data_pt as @goal_data_pt" do
        post :create, {:goal_data_pt => invalid_attributes}, valid_session
        expect(assigns(:goal_data_pt)).to be_a_new(GoalDataPt)
      end

      it "re-renders the 'new' template" do
        post :create, {:goal_data_pt => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested goal_data_pt" do
        goal_data_pt = GoalDataPt.create! valid_attributes
        put :update, {:id => goal_data_pt.to_param, :goal_data_pt => new_attributes}, valid_session
        goal_data_pt.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested goal_data_pt as @goal_data_pt" do
        goal_data_pt = GoalDataPt.create! valid_attributes
        put :update, {:id => goal_data_pt.to_param, :goal_data_pt => valid_attributes}, valid_session
        expect(assigns(:goal_data_pt)).to eq(goal_data_pt)
      end

      it "redirects to the goal_data_pt" do
        goal_data_pt = GoalDataPt.create! valid_attributes
        put :update, {:id => goal_data_pt.to_param, :goal_data_pt => valid_attributes}, valid_session
        expect(response).to redirect_to(goal_data_pt)
      end
    end

    context "with invalid params" do
      it "assigns the goal_data_pt as @goal_data_pt" do
        goal_data_pt = GoalDataPt.create! valid_attributes
        put :update, {:id => goal_data_pt.to_param, :goal_data_pt => invalid_attributes}, valid_session
        expect(assigns(:goal_data_pt)).to eq(goal_data_pt)
      end

      it "re-renders the 'edit' template" do
        goal_data_pt = GoalDataPt.create! valid_attributes
        put :update, {:id => goal_data_pt.to_param, :goal_data_pt => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested goal_data_pt" do
      goal_data_pt = GoalDataPt.create! valid_attributes
      expect {
        delete :destroy, {:id => goal_data_pt.to_param}, valid_session
      }.to change(GoalDataPt, :count).by(-1)
    end

    it "redirects to the goal_data_pts list" do
      goal_data_pt = GoalDataPt.create! valid_attributes
      delete :destroy, {:id => goal_data_pt.to_param}, valid_session
      expect(response).to redirect_to(goal_data_pts_url)
    end
  end

end
